#!/bin/sh

cd /var/www/html

composer install

php -r "file_exists('.env') || copy('.env.example', '.env');"

if grep -Fxq "APP_KEY=" .env
then
  php artisan key:generate
fi

php artisan optimize:clear

php artisan event:cache
php artisan config:cache
php artisan route:cache

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
